general:
  project_name: object_detection_mobilenet
  model_type: st_ssd_mobilenet_v1
  # model_path: 
  saved_models_dir: saved_models
  # gpu_memory_limit: 16
  global_seed: 127
  logs_dir: logs

operation_mode: training

dataset:
   name: Road_Sign_Detection    
   class_names: [trafficlight, stop, speedlimit, crosswalk]
   training_path: ../datasets/road-sign-darknet/train/
   validation_path: 
   validation_split: 0.2
   test_path: ../datasets/road-sign-darknet/valid/
   quantization_path: 
   quantization_split: 

preprocessing:
  rescaling:
    scale: 1/127.5
    offset: -1
  resizing:
    interpolation: nearest
    aspect_ratio: fit
  color_mode: rgb

data_augmentation:
  rotation: 30
  shearing: 15
  translation: 0.1
  vertical_flip: 0.5
  horizontal_flip: 0.2
  gaussian_blur: 3.0
  linear_contrast: [ 0.75, 1.5 ]

training:
  model:
    alpha: 0.25
    input_shape: (192, 192, 3)
    pretrained_weights: imagenet
  dropout:
  frozen_layers: (0, -1)
  batch_size: 64
  epochs: 1000
  optimizer:
    Adam:
      learning_rate: 0.001
  callbacks:
    ReduceLROnPlateau:
      monitor: val_loss
      factor: 0.1
      patience: 20
    EarlyStopping:
      monitor: val_loss
      mode: min
      restore_best_weights: True
      patience: 40

postprocessing:
  confidence_thresh: 0.6
  NMS_thresh: 0.5
  IoU_eval_thresh: 0.3
  plot_metrics: True   # Plot precision versus recall curves. Default is False.
  max_detection_boxes: 10
  
mlflow:
   uri: ./experiments_outputs/mlruns

hydra:
   run:
      dir: ./experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}
